apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  namespace: default
  labels:
    app: java
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: demo:${VERSION}
          ports:
            - containerPort: 8080
              name: java
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            failureThreshold: 1
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /status
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:

  labels:
    app: java
  name: java
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java
  sessionAffinity: None
  type: LoadBalancer